"""Inexact-Hessian oracle wrapper.

Wraps a :class:`BaseSmoothOracle` so that ``oracle.hess(x)`` returns
``nabla^2 f(x) + E`` where ``E`` is a deterministic symmetric
perturbation with spectral norm exactly ``delta_budget``.  The function
value and gradient oracles are forwarded unchanged.

The perturbation is generated by a private :class:`numpy.random.Generator`
seeded at construction, so:

* Two re-runs of the same problem with the same ``noise_seed`` produce
  identical perturbation sequences and therefore identical (modulo
  wall-clock) trajectories.
* Two runs with different ``delta_budget`` values but the same seed
  share the same realisation of the noise pattern (re-scaled), which
  makes the noise-floor structure visible across a delta sweep.

When ``delta_budget == 0`` the wrapper is a no-op.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

from agns.oracles.base import BaseSmoothOracle

__all__ = ["InexactHessianOracle"]


class InexactHessianOracle(BaseSmoothOracle):
    """Wrap ``base`` so that ``hess(x)`` returns ``nabla^2 f(x) + E``.

    ``E`` is a fresh symmetric matrix per call with spectral norm
    exactly ``delta_budget``.  The internal RNG is seeded so re-runs
    are bit-reproducible.

    Parameters
    ----------
    base : BaseSmoothOracle
        The exact-Hessian oracle to wrap.
    delta_budget : float
        Non-negative spectral-norm bound on the perturbation.  ``0.0``
        makes the wrapper a no-op.
    noise_seed : int
        Seed for the perturbation RNG.  Two oracles with the same seed
        produce identical perturbation sequences.

    Notes
    -----
    * ``func(x)`` and ``grad(x)`` are forwarded verbatim.
    * ``hess_vec(x, v)`` is forwarded *without* perturbation.  AGNS-Theory
      and its wrappers materialise the full Hessian via ``hess()`` (so
      they see the perturbed matrix); methods that rely on ``hess_vec``
      see the exact Hessian.
    * Other oracle attributes (``func_u``, ``jac_u``, ``p``, ...) fall
      through to the wrapped oracle via :meth:`__getattr__`.
    """

    def __init__(
        self,
        base: BaseSmoothOracle,
        delta_budget: float,
        noise_seed: int = 0,
    ) -> None:
        if delta_budget < 0.0:
            raise ValueError(f"delta_budget must be non-negative, got {delta_budget}")
        self.base = base
        self.delta_budget = float(delta_budget)
        self._rng = np.random.default_rng(noise_seed)

    def func(self, x: NDArray[np.float64]) -> float:
        return self.base.func(x)

    def grad(self, x: NDArray[np.float64]) -> NDArray[np.float64]:
        return self.base.grad(x)

    def hess_vec(self, x: NDArray[np.float64], v: NDArray[np.float64]) -> NDArray[np.float64]:
        return self.base.hess_vec(x, v)

    def hess(self, x: NDArray[np.float64]) -> NDArray[np.float64]:
        H = self.base.hess(x)
        if self.delta_budget <= 0.0:
            return H
        n = H.shape[0]
        A = self._rng.standard_normal((n, n)) / np.sqrt(n)
        E = (A + A.T) * 0.5
        spectral_norm = float(np.linalg.norm(E, ord=2))
        if spectral_norm > 0.0:
            E *= self.delta_budget / spectral_norm
        return H + E

    def __getattr__(self, name: str) -> object:
        return getattr(self.base, name)
