# Real-world LIBSVM benchmark on the ``madelon`` dataset.

include:
  - ../_base/problems/logistic_regression_libsvm.yaml

problem:
  params:
    path: data/binary/madelon
    reg: 0.001
    max_samples: null

common:
  gamma_0: 1.0
  eps: 1.0e-10
  adaptive_search: true

methods:
  - include: [../_base/methods/gns_exact.yaml]
    n_iters: 150
  - include: [../_base/methods/agns_inexact.yaml]
    n_iters: 150
  - include: [../_base/methods/agns_exact.yaml]
    n_iters: 150
  - include: [../_base/methods/agns_exact_norestart.yaml]
    n_iters: 150
  - include: [../_base/methods/agns_inexact_norestart.yaml]
    n_iters: 150
  - include: [../_base/methods/super_newton.yaml]
    n_iters: 150
  - include: [../_base/methods/newton.yaml]
    n_iters: 150
  - include: [../_base/methods/lbfgs.yaml]
    n_iters: 500
  - include: [../_base/methods/trust_region.yaml]
    n_iters: 150
  - include: [../_base/methods/accelerated_cubic_newton.yaml]
    n_iters: 150
  - include: [../_base/methods/gradient.yaml]
    n_iters: 1500
  - include: [../_base/methods/fast_gradient.yaml]
    n_iters: 1500

output:
  save_dir: results/numerical/raw/real_lr_madelon
  title: "Logistic regression on madelon (LIBSVM)"
